<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Linux.Bluetooth" Version="5.67.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Lionk\src\Lib\Lionk.Core\Lionk.Core.csproj" />
    </ItemGroup>

</Project>
